/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDPPH0IasV4FbpC1RLYFi58A",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-08360ec775bfda338",
            securityGroupIds: [
                "sg-08b5d1a45f34c0f5c"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-051b133ace54ba4e6",
                    availabilityZone: "us-east-1c"
                },
                {
                    subnetId: "subnet-0f38d28e78608974d",
                    availabilityZone: "us-east-1e"
                },
                {
                    subnetId: "subnet-082fa94667adc6581",
                    availabilityZone: "us-east-1b"
                },
                {
                    subnetId: "subnet-09a1ac5236e70d02a",
                    availabilityZone: "us-east-1a"
                },
                {
                    subnetId: "subnet-0969b5008a8f6235f",
                    availabilityZone: "us-east-1f"
                },
                {
                    subnetId: "subnet-012698081567feada",
                    availabilityZone: "us-east-1d"
                }
            ]
        }
    }
}).schema({
    "users": a.model({
        id: a.integer().default(),
        email: a.string().required(),
        hashed_password: a.string().required(),
        is_active: a.boolean(),
        stripe_customer_id: a.string(),
        stripe_subscription_id: a.string(),
        stripe_subscription_item_id: a.string(),
        created_at: a.string()
    }).identifier([
        "id"
    ])
});
