#DATABASE_URL=postgresql://username:password@localhost:5432/fifo_saas_db
DATABASE_URL=postgresql://neondb_owner:npg_lDufWE50JQXc@ep-restless-waterfall-a4gec24c-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
JWT_SECRET=supersecretjwtkey
JWT_EXP_SECONDS=3600
STRIPE_PRICE_METERED_ID=price_xxx
STRIPE_SECRET_KEY=sk_test_xxx
STRIPE_WEBHOOK_SECRET=whsec_xxx
FRONTEND_URL=http://localhost:5173
REACT_APP_API_URL=http://localhost:8080
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxx
AWS_REGION=us-east-1
S3_BUCKET_NAME=fifo-saas-outputs
PROD_ENV=development
USER_TABLE_NAME=users
DYNAMODB_LOCAL_URL=http://host.docker.internal:8000